/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 *  SRv6 Mobile User Plane implementation
 */
#ifndef _UAPI_LINUX_SEG6_MOBILE_H
#define _UAPI_LINUX_SEG6_MOBILE_H

enum {
	SEG6_MOBILE_UNSPEC,
	SEG6_MOBILE_ACTION,
	SEG6_MOBILE_NH6,
	SEG6_MOBILE_COUNTERS,
	SEG6_MOBILE_SRC_ADDR,
	SEG6_MOBILE_V4_MASK_LEN,
	SEG6_MOBILE_PDU_TYPE,
	SEG6_MOBILE_V6_SRC_PREFIX_LEN,
	SEG6_MOBILE_SRH,
	SEG6_MOBILE_SR_PREFIX_LEN,
	__SEG6_MOBILE_MAX,
};

#define SEG6_MOBILE_MAX	(__SEG6_MOBILE_MAX - 1)

enum {
	SEG6_MOBILE_ACTION_UNSPEC	= 0,
	/* swap IPv6 DA with the next SID, leave SRH untouched */
	SEG6_MOBILE_ACTION_END_MAP	= 1,
	/* SRv6 to IPv4/GTP-U encap */
	SEG6_MOBILE_ACTION_END_M_GTP4_E	= 2,
	/* SRv6 to IPv6/GTP-U encap */
	SEG6_MOBILE_ACTION_END_M_GTP6_E	= 3,
	/* IPv6/GTP-U decap into SR Policy */
	SEG6_MOBILE_ACTION_END_M_GTP6_D	= 4,
	/* IPv6/GTP-U drop-in decap into SR Policy */
	SEG6_MOBILE_ACTION_END_M_GTP6_D_DI	= 5,

	__SEG6_MOBILE_ACTION_MAX,
};

#define SEG6_MOBILE_ACTION_MAX	(__SEG6_MOBILE_ACTION_MAX - 1)

enum {
	SEG6_MOBILE_CNT_UNSPEC,
	SEG6_MOBILE_CNT_PACKETS,
	SEG6_MOBILE_CNT_BYTES,
	SEG6_MOBILE_CNT_ERRORS,
	SEG6_MOBILE_CNT_PAD,
	__SEG6_MOBILE_CNT_MAX,
};

#define SEG6_MOBILE_CNT_MAX	(__SEG6_MOBILE_CNT_MAX - 1)

#endif /* _UAPI_LINUX_SEG6_MOBILE_H */
